version: 2

references:

base_image: &base_image
  hashicorp/terraform:light

default_config: &default_config
  docker:
    - image: *base_image
  working_directory: ~/infra

setup_credentials: &setup_credentials
  run:
    name: Setup terraform credentials
    command: echo $SERVICE_ACCOUNT_CONTENT | base64 -d > credentials/account.json


jobs:
  staging_common_init:
    <<: *default_config
    steps:
      - checkout
      - *setup_credentials
      - run:
          name: Terraform Init
          command: |
            echo $(pwd)
            cd environments/staging/common
            terraform init -input=false

  staging_common_plan:
    <<: *default_config
    steps:
      - checkout
      - *setup_credentials
      - run:
          name: Terraform Plan
          command: |
            cd environments/staging/common
            terraform plan -input=false

workflows:
  version: 2
  init_plan_:
    jobs:
      - staging_common_init
      - staging_common_plan:
          requires:
            - staging_common_init
