version: 2

references:

working_directory: &working_directory
  ~/infra

base_image: &base_image
  hashicorp/terraform:light

default_config: &default_config
  docker:
    - image: *base_image
  working_directory: *working_directory

setup_credentials: &setup_credentials
  run:
    name: Setup terraform credentials
    command: echo $SERVICE_ACCOUNT_CONTENT | base64 -d > credentials/account.json

repo_cache_key: &repo_cache_key
  v1-repo-{{ .Branch }}-{{ .Revision }}

restore_repo: &restore_repo
  restore_cache:
    key: *repo_cache_key

save_repo: &save_repo
  save_cache:
    key: *repo_cache_key
    paths:
      - *working_directory

jobs:
  staging_common_init:
    <<: *default_config
    steps:
      - checkout
      - *setup_credentials
      - run:
          name: Terraform Init
          command: |
            cd environments/staging/common
            terraform init -input=false
      - *save_repo

  staging_common_plan:
    <<: *default_config
    steps:
      - checkout
      - *restore_repo
      - *setup_credentials
      - run:
          name: Terraform Plan
          command: |
            cd environments/staging/common
            terraform plan -input=false
      - *save_repo

  staging_common_apply:
    <<: *default_config
    steps:
      - checkout
      - *restore_repo
      - *setup_credentials
      - run:
          name: Terraform Apply
          command: |
            cd environments/staging/common
            terraform apply -input=false
      - *save_repo

workflows:
  version: 2
  init_plan_apply:
    jobs:
      - staging_common_init
      - staging_common_plan:
          requires:
            - staging_common_init
      - approve:
          type: approval
          requires:
            - staging_common_plan
          filters:
            branches:
              only: master
      - staging_common_apply:
          requires:
            - approve
          filters:
            branches:
              only: master
