version: 2

references:

working_directory: &working_directory
  ~/infra

base_image: &base_image
  hashicorp/terraform:light

default_config: &default_config
  docker:
    - image: *base_image
  working_directory: *working_directory

common_cache_key: &common_cache_key
  staging-common-tfstate-{{ .Branch }}-{{ .Revision }}

common_state_folder: &common_state_folder
  environments/staging/common

services_cache_key: &services_cache_key
  staging-services-tfstate-{{ .Branch }}-{{ .Revision }}

services_state_folder: &services_state_folder
  environments/staging/services

restore_common_state: &restore_common_state
  restore_cache:
    key: *common_cache_key

save_common_state: &save_common_state
  save_cache:
    key: *common_cache_key
    paths:
      - *common_state_folder

restore_services_state: &restore_services_state
  restore_cache:
    key: *services_cache_key

save_services_state: &save_services_state
  save_cache:
    key: *services_cache_key
    paths:
      - *services_state_folder

setup_credentials: &setup_credentials
  run:
    name: Setup terraform credentials
    command: echo $SERVICE_ACCOUNT_CONTENT | base64 -d > credentials/account.json

terraform_init: &terraform_init
  run:
    name: Terraform init
    command: |
      cd environments/$ENVIRONMENT_MODULE
      terraform init -input=false

terraform_plan: &terraform_plan
  run:
    name: Terraform plan
    command: |
      cd environments/$ENVIRONMENT_MODULE
      terraform plan -input=false

terraform_apply: &terraform_apply
  run:
    name: Terraform apply
    command: |
      cd environments/$ENVIRONMENT_MODULE
      terraform apply -input=false

jobs:
  staging_common_init:
    <<: *default_config
    environment:
      ENVIRONMENT_MODULE: "staging/common"
    steps:
      - checkout
      - *setup_credentials
      - *terraform_init
      - *save_common_state

  staging_common_plan:
    <<: *default_config
    environment:
      ENVIRONMENT_MODULE: "staging/common"
    steps:
      - checkout
      - *restore_common_state
      - *setup_credentials
      - *terraform_plan
      - *save_common_state

  staging_common_apply:
    <<: *default_config
    environment:
      ENVIRONMENT_MODULE: "staging/common"
    steps:
      - checkout
      - *restore_common_state
      - *setup_credentials
      - *terraform_apply
      - *save_common_state

  staging_services_init:
    <<: *default_config
    environment:
      ENVIRONMENT_MODULE: "staging/services"
    steps:
      - checkout
      - *setup_credentials
      - *terraform_init
      - *save_services_state

  staging_services_plan:
    <<: *default_config
    environment:
      ENVIRONMENT_MODULE: "staging/services"
    steps:
      - checkout
      - *restore_services_state
      - *setup_credentials
      - *terraform_plan
      - *save_services_state

  staging_services_apply:
    <<: *default_config
    environment:
      ENVIRONMENT_MODULE: "staging/services"
    steps:
      - checkout
      - *restore_services_state
      - *setup_credentials
      - *terraform_apply
      - *save_services_state

workflows:
  version: 2
  init_plan_apply:
    jobs:
      - staging_common_init
      - staging_common_plan:
          requires:
            - staging_common_init
      - staging_services_init
      - staging_services_plan:
          requires:
            - staging_services_init
      - approve:
          type: approval
          requires:
            - staging_common_plan
            - staging_services_plan
          filters:
            branches:
              only: master
      - staging_common_apply:
          requires:
            - approve
          filters:
            branches:
              only: master
      - staging_services_apply:
          requires:
            - approve
            - staging_common_apply
          filters:
            branches:
              only: master
